require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "Rakefile"
    - "vendor/**/*"
    - "config.ru"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Layout/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 12

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/PredicateMatcher:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Rails/HasManyOrHasOneDependent:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7

Style/SymbolProc:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
